import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const ttRamillas = localFont({
  src: "../public/fonts/TT_Ramillas_Regular.ttf", // Adjust path to where you placed the file
  variable: "--font-ramillas",
  display: "swap",
});

// 2. Inter Medium (Clean UI / Navigation / Buttons)
const inter = localFont({
  src: "../public/fonts/Inter18pt-Medium.ttf",
  variable: "--font-inter",
  display: "swap",
});

// 3. Karla Light (Body copy / Paragraphs / Subtext)
const karla = localFont({
  src: "../public/fonts/Karla-Light.ttf",
  variable: "--font-karla",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${ttRamillas.variable} ${inter.variable} ${karla.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
